#!/bin/sh
 
set -e
 
# Must be a valid filename
NAME=domotix
PIDFILE=/var/run/$NAME.pid
DIR_NAME=/home/pi/panStamp/domotix

#This is the command to be run, give the full pathname
DAEMON=/usr/local/bin/node
DAEMON_OPTS="$DIR_NAME/app.js"
 
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    echo -n "Starting daemon: "$NAME
	start-stop-daemon --start --quiet --pidfile $PIDFILE -d $DIR_NAME --exec $DAEMON -- $DAEMON_OPTS
    echo "."
	;;
  stop)
    echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    echo "."
	;;
  restart)
    echo -n "Restarting daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "."
	;;
 
  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac
 
exit 0