#!/bin/sh
### BEGIN INIT INFO
# Provides:             domotix
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Domotix plugin
### END INIT INFO

export HOME=/home/pi/panStamp/domotix
export APP_FILE=$HOME/app.js

LOG_FILE=$HOME/logs/domotix_forever.log
LOG_OUT_FILE=$HOME/logs/domotix_out.log
LOG_ERR_FILE=$HOME/logs/domotix_err.log
LOG_SERVICE_FILE=$HOME/logs/domotix_service.log
PATH=/usr/local/bin:$PATH

# Required for socketstream
cd $HOME

case "$1" in
  start)
    rm -f $LOG_FILE
    rm -f $LOG_OUT_FILE
    rm -f $LOG_ERR_FILE
    rm -f $LOG_SERVICE_FILE
    forever start --uid "domotix" -l $LOG_FILE -o $LOG_OUT_FILE -e $LOG_ERR_FILE $APP_FILE
    RETVAL=$?
    ;;
  stop)
    /usr/local/bin/forever stop domotix
    RETVAL=$?
    ;;
  restart)
    rm -f $LOG_FILE
    rm -f $LOG_OUT_FILE
    rm -f $LOG_ERR_FILE
    rm -f $LOG_SERVICE_FILE
    /usr/local/bin/forever restart domotix
    RETVAL=$?
    ;;
  status)
    /usr/local/bin/forever list | grep $APP_FILE | wc -l | sed -e 's/1/App Running/' | sed -e 's/0/App not started/'
    ;;
  *)

  echo "Usage: /etc/init.d/domotix {start|stop|restart|status}"
  exit 1
  ;;
esac
#echo "`/bin/date` $1 $RETVAL" >> $HOME/logs/domotix_service.log
exit $RETVAL

