#!/bin/sh
# /etc/init.d/thingspeak

do_stop()
{
    echo "Killing thingspeak"
    pkill nodemon
}

do_start()
{
    echo "Starting thingspeak"
    cd /home/pi/panStamp/domotix
    /usr/local/bin/nodemon server/plugins/thingspeaksub >logs/thingspeak_c.log 2>&1 &
}

case "$1" in
    stop)
        do_stop
        ;;
    start)
        do_start
        ;;
     restart)
        do_stop 
        do_start
        ;; 
     *)
        echo "Usage: start|stop|restart"
        ;;
esac

exit 0
